# Global LLM configuration
[llm]
model = "moonshot-v1-128k"
base_url = "https://api.moonshot.cn/v1"
api_key = "sk-gjtNABtUMdf6djV9uLFgEwRRrDtTaEBdRE7QKf3D2zMZDIaL"
max_tokens = 4096
temperature = 0.0

# Optional configuration for specific LLM models
[llm.vision]
model = "moonshot-v1-128k-vision-preview"
base_url = "https://api.moonshot.cn/v1"
api_key = "sk-gjtNABtUMdf6djV9uLFgEwRRrDtTaEBdRE7QKf3D2zMZDIaL"

# OpenAI configuration
[openai]
model = "moonshot-v1-128k"
api_key = "sk-gjtNABtUMdf6djV9uLFgEwRRrDtTaEBdRE7QKf3D2zMZDIaL"
api_base = "https://api.moonshot.cn/v1"


# OpenManus configuration
[auth]
required = true  # 是否需要认证才能使用
base_url = "http://www.dlb.org.cn/auth"  # 认证服务基础URL
client_id = "client1"  # 客户端ID
client_secret = ""  # 客户端密钥
scope = "profile"  # 认证范围